add script, and change rules in eslint

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,48 +1,36 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-#!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
-
 echo '🏗️👷 Styling, testing and building your project before committing'
 
-# Check Prettier standards
-npm run check-format ||
+# Check ESLint AirBnb Standards
+npm run lint ||
 (
-    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
-            Prettier Check Failed. Run npm run format, add changes and try commit again.';
+    echo '🤢🤮🤢🤮 Yoo, your code looks disgusting. Check linter 🤢🤮🤢🤮
+          Run npm run lint, add changes and try commit again.';
     false;
 )
 
 # Check ESLint Standards
-npm run check-lint ||
+npm run type-check ||
 (
-        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤
-                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+        echo '😤🏀👋😤 Yooo, Type check failed! Fix it and try to commit again  😤🏀👋😤'
         false;
 )
 
-# Check tsconfig standards
-npm run check-types ||
-(
-    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
-            Are you seriously trying to write that? Make the changes required above.'
-    false;
-)
+# If everything passes... Now we can commit
+# echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
+
+# npm run build ||
+# (
+#    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
+#            Next build failed: View the errors above to see why.
+#    '
+#    false;
+#)
 
 # If everything passes... Now we can commit
-echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
-
-npm run build ||
-(
-    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
-            Next build failed: View the errors above to see why.
-    '
-    false;
-)
-
-# If everything passes... Now we can commit
-echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
+echo '🎉✨🚀 You win this time... I am committing this now. ✅✅✅✅'
 
 
 npx lint-staged
